[window]
# padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "None"
opacity = 1.0

[font]
# normal = { family = "Terminess Nerd Font Mono", style = "Bold" } 
# italic = { family = "Terminess Nerd Font Mono", style = "Bold" }  # Force italics to use bold
# normal = { family = "Zenbones Brainy", style = "normal" } 
# italic = { family = "Zenbones Brainy", style = "normal" }  # Force italics to use bold
normal = { family = "UbuntuMono Nerd Font", style = "normal" } 
italic = { family = "UbuntuMono Nerd Font", style = "normal" }  # Force italics to use bold
size = 19

# [colors.primary]
# background = '#000000'
# foreground = '#ffffff'

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[general]
live_config_reload = true
